/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUploadRouteImport } from './routes/_auth/upload'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthAdminOverviewRouteImport } from './routes/_auth/admin/overview'
import { Route as AuthAdminCustomersRouteImport } from './routes/_auth/admin/customers'
import { Route as AuthAdminAdminsRouteImport } from './routes/_auth/admin/admins'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminOverviewRoute = AuthAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminCustomersRoute = AuthAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAdminsRoute = AuthAdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/upload': typeof AuthUploadRoute
  '/admin/admins': typeof AuthAdminAdminsRoute
  '/admin/customers': typeof AuthAdminCustomersRoute
  '/admin/overview': typeof AuthAdminOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/upload': typeof AuthUploadRoute
  '/admin/admins': typeof AuthAdminAdminsRoute
  '/admin/customers': typeof AuthAdminCustomersRoute
  '/admin/overview': typeof AuthAdminOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/upload': typeof AuthUploadRoute
  '/_auth/admin/admins': typeof AuthAdminAdminsRoute
  '/_auth/admin/customers': typeof AuthAdminCustomersRoute
  '/_auth/admin/overview': typeof AuthAdminOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/upload'
    | '/admin/admins'
    | '/admin/customers'
    | '/admin/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/upload'
    | '/admin/admins'
    | '/admin/customers'
    | '/admin/overview'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/admin'
    | '/_auth/dashboard'
    | '/_auth/upload'
    | '/_auth/admin/admins'
    | '/_auth/admin/customers'
    | '/_auth/admin/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/overview': {
      id: '/_auth/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthAdminOverviewRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/customers': {
      id: '/_auth/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthAdminCustomersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/admins': {
      id: '/_auth/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthAdminAdminsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminAdminsRoute: typeof AuthAdminAdminsRoute
  AuthAdminCustomersRoute: typeof AuthAdminCustomersRoute
  AuthAdminOverviewRoute: typeof AuthAdminOverviewRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminAdminsRoute: AuthAdminAdminsRoute,
  AuthAdminCustomersRoute: AuthAdminCustomersRoute,
  AuthAdminOverviewRoute: AuthAdminOverviewRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthUploadRoute: typeof AuthUploadRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthUploadRoute: AuthUploadRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
